trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - '**/README.md'
    - LICENSE

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildContainer
    displayName: Build container

    jobs:
      - job: DockerJob
        displayName: Build and publish container image

        steps:

          - task: Docker@2
            displayName: Build and push image to container registry
            inputs:
              command: buildAndPush
              containerRegistry: MyContainerRegistry
              repository: docker-ghost-ai
              dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
                latest